### ISSUE TITLE
create repository for github testing

### ISSUE THREAD

**Issue by kcranston** [Reproducible-Science-Curriculum/rr-version-control#6]
@iamciera proposed (in issue #4) creating a repository for testing GitHub forks, commits and pull requests. I think that is a good idea. Perhaps a collection of science-related quotes?

**Comment by iamciera** [comment]
👍.  Quotes work well.  Let me know when you get the repository up, I will add my favorite science quote. 

Also, if you plan on using the new practice repo tomorrow, make sure it is an extra after session exercise, so they are not adding at the same time.  When a group of beginner git users all try to add to the same repo at the same time it can get ugly fast.

**Comment by kcranston** [comment]
Yeah, I am worried about this repo becoming a mess of merge conflicts (which can't be fixed in the GitHub UI). Thoughts on avoiding this?

**Comment by iamciera** [comment]
I really don't think there is a way to avoid the merge conflicts from everyone adding to the same repo at the same time.  That is why I had them pair up and add changes to each others' repos. This has worked well.  If you do the pairing exercise, make sure that each repo has a unique name (I have them add their name to the repo name) or else that exercise gets confusing fast too.

**Comment by fmichonneau** [comment]
GitHub just released: https://classroom.github.com/ 

It makes it easy to create a template repository and distributing many copies of it to groups of people  (e.g., pairs) so they can work on separate repos without having to worry too much about merge conflicts.
